{{- if or (.Values.service.enabled) (.Values.statefulset.enabled) }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "flex.fullname" . }}
  labels:
    {{- include "flex.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "flex.selectorLabels" . | nindent 4 }}

{{- end -}}
