{{- if or (.Values.service.enabled) (.Values.statefulset.enabled) }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "flex.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "flex.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: {{ .Values.container.protocol }}
      name: {{ .Values.container.name }}
  selector:
    {{- include "flex.selectorLabels" . | nindent 4 }}

{{- end -}}
